spring:
  application:
    name: honey-gateway

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: auth-route
          uri: lb://1aiot-auth2
          predicates:
            - Path=/auth/**
          filters:
            - name: Retry
              args:
                retries: 300
                statuses:
                  - SERVICE_UNAVAILABLE
                series:
                  - SERVER_ERROR

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG