spring:
  application:
    name: gateway-test

  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}

    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
      routes:
        - id: platform-route
          uri: lb://aiot-platform
          predicates:
            - Path=/platform/**
        - id: sys-route
          uri: lb://aiot-sys
          predicates:
            - Path=/sys/**
        - id: auth-route
          uri: lb://1aiot-auth23
          predicates:
            - Path=/auth/**